#!/usr/bin/with-contenv bash

DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-warning}
UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"

exec \
	s6-setuidgid abc /usr/bin/deluge-web -c /config \
	-d --loglevel=${DELUGE_LOGLEVEL} -l /config/deluge-web.log
