FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

RUN apk add --no-cache \
  gpsd \
  gpsd-clients \
  chrony

COPY chrony.conf /etc/chrony

ENV UDEV on

#CMD while : ; do echo "${MESSAGE=Idling...}"; sleep ${INTERVAL=600}; done
ENTRYPOINT ["/bin/bash"]
